language: java
jdk: oraclejdk11

matrix:
  include:
    - os: linux
      language: java

    - os: windows
      language: shell
      env: CHOCO_PACKAGES=jdk11 GRADLE_OPTS=-Dorg.gradle.daemon=false

    - os: osx
      language: java

install:
  - ./.travis/install.sh

script:
  - bash gradlew check
