language: java
jdk: openjdk11

matrix:
  include:
    - os: linux
      language: java

    - os: windows
      language: shell
      filter_secrets: false
      install:
        - choco install openjdk11
        - export JAVA_HOME="C:/Program Files/OpenJDK/jdk-11.0.2"
        - export PATH="${PATH}:/c/Program Files/OpenJDK/jdk-11.0.2/bin"
      script:
        - bash gradlew --no-daemon check

    - os: osx
      language: java
